#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          lima-os-monitoring
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OS monitoring (cpu/hdd/mem/net) with StatsD
# Description:       OS monitoring (cpu/hdd/mem/net) with StatsD
### END INIT INFO

# Author: Jacek Kopecky <jacek.kopecky@port.ac.uk>

NAME="lima os monitoring"
DAEMON=/home/lima/living-meta-analysis/deployment/shared/monitoring-os-scripts/monitor.sh

PIDFILE="/var/run/lima/lima-os-monitoring.pid"
LOGFILE="/var/log/lima/lima-os-monitoring.log"


start() {
    echo "Starting $NAME"
    "$DAEMON" >> $LOGFILE 2>&1 &
    RETVAL=$?
    mkdir -p `dirname $PIDFILE`
    echo $! > $PIDFILE
}

stop() {
    if [ -f $PIDFILE ]; then
        echo "Shutting down $NAME"
	kill -1 `cat $PIDFILE`
        rm -f $PIDFILE
        RETVAL=0
    else
        echo "$NAME is not running."
        RETVAL=0
    fi
}

restart() {
    stop
    start
}

status() {
    if [ -e "$PIDFILE" ]
    then
        echo "$NAME is probably running."
        RETVAL=0
    else
        echo "$NAME is not running."
        RETVAL=3
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
